version: '3'

services:
  mysql:
    image: mysql:8
    restart: always
    container_name: mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: 'db1'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge