version: '3'

services:
  mysql:
    image: mysql:8
    restart: always
    container_name: financial-mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: 'financial'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - .\:/docker-entrypoint-initdb.d
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge